language: java
jdk:
  - openjdk8
#Travis CI를 어느 브랜치가 푸시될때 수행될지 지정합니다.addons:
#현재 옵션은 오직 master 브랜치에 push 될때만 수행 합니다.
branches:
  only:
    - master
before_install:
  - chmod +x gradlew
# Travis CI 서버의 Home
# 그레이들을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여,같은 의존성은 다음배포 때부터 다시 받지 않도록 설정합니다.
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
# master 브랜치에 푸시되었을때 수행하는 명령어 입니다.
# 여기서는 프로젝트 내부에 둔 gradlew을 통해 clean & build 를 수행합니다.
script: "./gradlew clean build"

#CI 실행완료시 메일로 알람
#Travis CI 실행 완료시 자동으로 알람이 가도록 설정합니다.
notifications:
  email:
    recipients: suwhean@gmail.com