language: java
jdk:
  - openjdk8
#Travis CI를 어느 브랜치가 푸시될때 수행될지 지정합니다.addons:
#현재 옵션은 오직 master 브랜치에 push 될때만 수행 합니다.
branches:
  only:
    - master
before_install:
  - chmod +x gradlew
# Travis CI 서버의 Home
# 그레이들을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여,같은 의존성은 다음배포 때부터 다시 받지 않도록 설정합니다.
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
# master 브랜치에 푸시되었을때 수행하는 명령어 입니다.
# 여기서는 프로젝트 내부에 둔 gradlew을 통해 clean & build 를 수행합니다.
script: "./gradlew clean build"

# deploy 명령어가 실행되기 전에 수행된니다.
# CodeDeploy 는 Jar 파일은 인식하지 못하므로 Jar+ 기타설정파일들을 모아 압축(zip) 합니다.
before_deploy:
  # Travis CI 는 S3로 특정파일만 업로드가 안됩니다.
  # 디렉토리 단위로만 업로드할 수 있기 때문에 deploy 디렉토리는 항상 생성합니다.
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
  # before-deploy 에는 zip 에 포함시킬 파일들을 저장합니다.
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  # zip -r 명령어를 통해 before-deploy 디렉토리 전체파일을 압축합니다.
  - cd before-deploy && zip -r before-deploy * #before-deploy 로 이동후 전체 압축
  - cd ../ && mkdir -p deploy #상위 디렉토리로 이동 후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/freelec-springboot2-webservice.zip #deploy로 zip 파일 이동

# S3로 파일 업로드 혹은 CodeDeploy로 배포 등 외부 서비스와 연동될 행위들을 선언합니다.
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: suhwankim-freelec-springboot-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl : private #zip 파일 접근을 private으로
    # 해당위치의 파일들만 S3로 전송합니다.
    local_dir: deploy #before_deploy 에서 생성한 디렉토리
    wait-until-deployed : true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY #Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: suhwankim-freelec-springboot-build # S3 버킷
    key : freelec-springboot2-webservice.zip #빌드 파일을 압축해서 전달
    bundle_type : zip #압축 확장자
    application : freelec-springboot2-webservice  # 웹콘솔에서 등록한 CodeDeploy 애플리케이션
    deployment_group : freelec-springboot2-webservice-group #웹콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed : true

#CI 실행완료시 메일로 알람
#Travis CI 실행 완료시 자동으로 알람이 가도록 설정합니다.
notifications:
  email:
    recipients: suwhean@gmail.com
